### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by juanmirocks** [gangstead/atom-scala-format#9]
Nothing happens if I try to open a wrongly-formatted `.scala` file.

Atom version: 0.194.0

I read the following deprecation calls:

```
Call ::getActiveTextEditor instead
Called 23 timesCreate Issue on scala-format repo
Workspace.getActiveEditor - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:999:12
atom-workspace.module.exports.format - /Users/jmcejuela/.atom/packages/scala-format/lib/scala-format.js:49:35
CommandRegistry.module.exports.CommandRegistry.handleCommandEvent - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29
<unknown> - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61

Call ::getActiveTextEditor instead
Called 23 timesCreate Issue on scala-format repo
Workspace.getActiveEditor - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:999:12
atom-workspace.module.exports.format - /Users/jmcejuela/.atom/packages/scala-format/lib/scala-format.js:49:71
CommandRegistry.module.exports.CommandRegistry.handleCommandEvent - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29
<unknown> - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
```

**Comment by juanmirocks** [comment]
Apparently it works indeed only if the file is saved, and then only slow.

I guess you can close this issue...

**Comment by gangstead** [comment]
Weird, those calls weren't showing the deprecation warnings for me.  I updated them anyways.  Thanks for the issue.

Eventually I'm going to work on the feature to have it format the buffer instead of from the saved file... someday.  Also the formatting library is in a jar that has to be launched in another process so it's never going to be as fast as a formatter done completely in JS.  I'm afraid I'm not smart enough to do that by myself so that's why I use the more-or-less standard scalariform library.

Again thanks for submitting the issue.

**Comment by juanmirocks** [comment]
Cheers. I think not reinventing the wheel and using an existing solution is the smart thing to do.

Only, indeed, perhaps the best thing would be to keep the spawned jvm running. Ideally, other services would use the same jvm, such as the `linter-scalac` package. Of course, this mean turning Atom more into an IDE and it's complex. Anyway.

Thanks for the package!
